---
name: Automerge release bump PR

env:
  GH_USER: jonaslagoni
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted

jobs:
  # Required if repository require reviews of PR's
  autoapprove:
    if: github.event.pull_request.draft == false && github.event.pull_request.user.login == 'jonaslagoni' && !contains(github.event.pull_request.labels.*.name, 'released')
    runs-on: ubuntu-latest
    steps:
      - name: Autoapproving
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: "${{ secrets.GH_TOKEN }}"

      - name: Label autoapproved
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['autoapproved']
            })
  automerge:
    needs: [autoapprove]
    if: github.event.pull_request.user.login == 'jonaslagoni'
    runs-on: ubuntu-latest
    steps:
      - name: Automerging
        uses: pascalgn/automerge-action@v0.13.0
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          GITHUB_LOGIN: ${{ env.GH_USER }}
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "20"
          MERGE_RETRY_SLEEP: "30000"
