---
name: Lint PR yaml files

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows** action.yml
          no_warnings: true
          config_data: "{extends: default, rules: {line-length: disable}}"
